//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace postCardCenterSdk.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("postCardCenterSdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 /backStyle 的本地化字符串。
        /// </summary>
        public static string backStyleListUrl {
            get {
                return ResourceManager.GetString("backStyleListUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://localhost:8087 的本地化字符串。
        /// </summary>
        public static string baseURI {
            get {
                return ResourceManager.GetString("baseURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /order/changeProcessor 的本地化字符串。
        /// </summary>
        public static string changeOrderProcessorUrl {
            get {
                return ResourceManager.GetString("changeOrderProcessorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /order/changeStatus 的本地化字符串。
        /// </summary>
        public static string changeOrderStatusUrl {
            get {
                return ResourceManager.GetString("changeOrderStatusUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /postCard/updateFrontStyle 的本地化字符串。
        /// </summary>
        public static string changePostCardFrontStyle {
            get {
                return ResourceManager.GetString("changePostCardFrontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /file/crop 的本地化字符串。
        /// </summary>
        public static string cropInfoSubmitUrl {
            get {
                return ResourceManager.GetString("cropInfoSubmitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /envelope/info?envelopeId={envelopeId} 的本地化字符串。
        /// </summary>
        public static string envelopeInfoUrl {
            get {
                return ResourceManager.GetString("envelopeInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /file 的本地化字符串。
        /// </summary>
        public static string fileDownloadUrl {
            get {
                return ResourceManager.GetString("fileDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /file 的本地化字符串。
        /// </summary>
        public static string fileInfoUrl {
            get {
                return ResourceManager.GetString("fileInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /file/upload 的本地化字符串。
        /// </summary>
        public static string fileUploadUrl {
            get {
                return ResourceManager.GetString("fileUploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /order/{orderId} 的本地化字符串。
        /// </summary>
        public static string getAllEnvelopeByOrderIdUrl {
            get {
                return ResourceManager.GetString("getAllEnvelopeByOrderIdUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /order/getAll 的本地化字符串。
        /// </summary>
        public static string getAllOrderUrl {
            get {
                return ResourceManager.GetString("getAllOrderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /size/{category} 的本地化字符串。
        /// </summary>
        public static string getAllProductSizeUrl {
            get {
                return ResourceManager.GetString("getAllProductSizeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /file/generateThumbnail/{fileId} 的本地化字符串。
        /// </summary>
        public static string getFileThumbnailUrl {
            get {
                return ResourceManager.GetString("getFileThumbnailUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /order/info?orderId={orderId} 的本地化字符串。
        /// </summary>
        public static string getOrderInfoUrl {
            get {
                return ResourceManager.GetString("getOrderInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /postCard/byEnvelopeId/{envelopeId} 的本地化字符串。
        /// </summary>
        public static string getPostCardByEnvelopeIdUrl {
            get {
                return ResourceManager.GetString("getPostCardByEnvelopeIdUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /postCard/info/{fileId} 的本地化字符串。
        /// </summary>
        public static string getPostCardInfoUrl {
            get {
                return ResourceManager.GetString("getPostCardInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /size/{category} 的本地化字符串。
        /// </summary>
        public static string insertSizeUrl {
            get {
                return ResourceManager.GetString("insertSizeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /security/login 的本地化字符串。
        /// </summary>
        public static string loginUrl {
            get {
                return ResourceManager.GetString("loginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /postCard/info 的本地化字符串。
        /// </summary>
        public static string patchPostCardInfoUrl {
            get {
                return ResourceManager.GetString("patchPostCardInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /order/submit 的本地化字符串。
        /// </summary>
        public static string postCardSubmitUrl {
            get {
                return ResourceManager.GetString("postCardSubmitUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /postCard/submitProduct 的本地化字符串。
        /// </summary>
        public static string productFileSubmitUrl {
            get {
                return ResourceManager.GetString("productFileSubmitUrl", resourceCulture);
            }
        }
    }
}
